# Generated by Django 6.0.6 on 2026-06-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_type_situation_code_type_affectation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_situation',
            name='code_type_situation',
            field=models.CharField(max_length=100),
        ),
    ]
