# Generated by Django 6.0.6 on 2026-07-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_regularisation_gm_code_regularisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='montant_chomage',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='montant_panne',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='montant_service',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='taux_location',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
    ]
