# Generated by Django 6.0.6 on 2026-07-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_pointage_montant_chomage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grand_materiel',
            name='taux_amortissement',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
