# Generated by Django 6.0.6 on 2026-07-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_grand_materiel_taux_amortissement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation_materiel',
            name='nbr_jours_affectation',
            field=models.IntegerField(default=0),
        ),
    ]
