# Generated by Django 6.0.6 on 2026-08-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_situation_materiel_id_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularisation_gm',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
