# Generated by Django 6.0.6 on 2026-08-12 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_regularisation_gm_observation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('IMPORT', 'Import'), ('VALIDATE', 'Validation'), ('CANCEL', 'Annulation')], max_length=20)),
                ('module', models.CharField(choices=[('MATERIEL', 'Matériel'), ('AFFECTATION', 'Affectation'), ('SITUATION', 'Situation'), ('POINTAGE', 'Pointage'), ('REGULARISATION', 'Régularisation'), ('IMPORT', 'Import'), ('UTILISATEUR', 'Utilisateur'), ('ADMINISTRATION', 'Administration'), ('MARQUE', 'Marque'), ('TYPE_MARQUE', 'Type de Marque'), ('SOUS_FAMILLE', 'Sous-Famille'), ('SITE', 'Site'), ('SITUATION_AFFECTATION', 'Situation Affectation')], max_length=25)),
                ('objet_type', models.CharField(max_length=100)),
                ('objet_id', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ancienne_valeur', models.JSONField(blank=True, null=True)),
                ('nouvelle_valeur', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('code_filiale', models.CharField(blank=True, max_length=100, null=True)),
                ('code_site', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
                'ordering': ['-date_action'],
            },
        ),
    ]
