# Generated by Django 6.0.6 on 2026-09-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_migrate_permissions_to_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_landing_page',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_visited_page',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='remember_last_visited_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('IMPORT', 'Import')], max_length=20),
        ),
        migrations.AlterField(
            model_name='journal',
            name='module',
            field=models.CharField(choices=[('MATERIEL', 'Matériel'), ('AFFECTATION', 'Affectation'), ('SITUATION', 'Situation'), ('POINTAGE', 'Pointage'), ('REGULARISATION', 'Régularisation'), ('UTILISATEUR', 'Utilisateur'), ('ADMINISTRATION', 'Administration'), ('MARQUE', 'Marque'), ('TYPE_MARQUE', 'Type de Marque'), ('SOUS_FAMILLE', 'Sous-Famille'), ('SITE', 'Site'), ('SITUATION_AFFECTATION', 'Situation Affectation'), ('FAMILLE', 'Famille'), ('CATEGORIE', 'Catégorie'), ('TYPE_ETAT', "Type d'État")], max_length=25),
        ),
    ]
