# Generated by Django 6.0.6 on 2026-09-03 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_userprofile_default_landing_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation_materiel',
            name='code_site',
            field=models.ForeignKey(blank=True, db_column='code_site', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='api.site', to_field='code_site'),
        ),
    ]
