# Generated by Django 6.0.6 on 2026-06-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='heures_chomage',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='heures_panne',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='heures_service',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
