# Generated by Django 6.0.6 on 2026-06-23 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pointage_heures_chomage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_situation',
            name='code_type_affectation',
            field=models.ForeignKey(db_column='code_type_affectation', on_delete=django.db.models.deletion.PROTECT, related_name='types_situation', to='api.type_affectation', to_field='code_type_affectation'),
        ),
        migrations.AddConstraint(
            model_name='type_situation',
            constraint=models.UniqueConstraint(fields=('code_type_affectation', 'code_type_situation'), name='unique_affectation_situation'),
        ),
    ]
