# Generated by Django 6.0.6 on 2026-06-24 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_type_situation_code_type_situation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='situation_materiel',
            old_name='code_situation',
            new_name='id_situation',
        ),
        migrations.RemoveField(
            model_name='situation_materiel',
            name='code_type_affectation',
        ),
        migrations.RemoveField(
            model_name='situation_materiel',
            name='code_type_situation',
        ),
        migrations.RemoveField(
            model_name='situation_materiel',
            name='libelle_situation',
        ),
        migrations.AddField(
            model_name='situation_materiel',
            name='affectation_id',
            field=models.ForeignKey(db_column='affectation_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='situation_ids', to='api.affectation_materiel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situation_materiel',
            name='date_situation',
            field=models.DateTimeField(default='2000-01-01 00:00:00.000000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situation_materiel',
            name='type_situation_id',
            field=models.ForeignKey(db_column='type_situation_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='situation_ids', to='api.type_situation'),
            preserve_default=False,
        ),
    ]
