# Generated by Django 6.0.6 on 2026-06-24 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_code_situation_situation_materiel_id_situation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularisation_gm',
            name='code_regularisation',
        ),
        migrations.AlterField(
            model_name='regularisation_gm',
            name='code_site',
            field=models.ForeignKey(db_column='code_site', on_delete=django.db.models.deletion.PROTECT, related_name='regularisations', to='api.site', to_field='code_site'),
        ),
        migrations.AddConstraint(
            model_name='regularisation_gm',
            constraint=models.UniqueConstraint(fields=('code_site', 'mmaa'), name='unique_site_mmaa'),
        ),
    ]
