# Generated by Django 6.0.6 on 2026-07-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_grand_materiel_taux_amortissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='date_modification',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='montant_chomage',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='montant_panne',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='montant_service',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='taux_location',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
    ]
