# Generated by Django 6.0.6 on 2026-07-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_pointage_date_modification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grand_materiel',
            name='taux_amortissement',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='grand_materiel',
            name='valeur_acquisition',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='grand_materiel',
            name='valeur_remplacement',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
