# Generated by Django 6.0.6 on 2026-07-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_affectation_materiel_nbr_jours_affectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation_materiel',
            name='id_situation',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
