# Generated by Django 6.0.6 on 2026-08-16 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_journal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='affectation_materiel',
            index=models.Index(fields=['code_affectation'], name='api_affecta_code_af_fa0f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='affectation_materiel',
            index=models.Index(fields=['code_materiel'], name='api_affecta_code_ma_22bbbf_idx'),
        ),
        migrations.AddIndex(
            model_name='affectation_materiel',
            index=models.Index(fields=['code_site'], name='api_affecta_code_si_33e4bb_idx'),
        ),
        migrations.AddIndex(
            model_name='affectation_materiel',
            index=models.Index(fields=['code_filiale_mere'], name='api_affecta_code_fi_a493e1_idx'),
        ),
        migrations.AddIndex(
            model_name='affectation_materiel',
            index=models.Index(fields=['date_affectation'], name='api_affecta_date_af_35a6ee_idx'),
        ),
        migrations.AddIndex(
            model_name='affectation_materiel',
            index=models.Index(fields=['est_bloque'], name='api_affecta_est_blo_304f93_idx'),
        ),
        migrations.AddIndex(
            model_name='affectation_materiel',
            index=models.Index(fields=['prenable'], name='api_affecta_prenabl_f477a8_idx'),
        ),
        migrations.AddIndex(
            model_name='affectation_materiel',
            index=models.Index(fields=['code_affectation', 'code_site'], name='api_affecta_code_af_ebecd5_idx'),
        ),
        migrations.AddIndex(
            model_name='grand_materiel',
            index=models.Index(fields=['code_materiel'], name='api_grand_m_code_ma_1a0d62_idx'),
        ),
        migrations.AddIndex(
            model_name='grand_materiel',
            index=models.Index(fields=['code_sous_famille_materiel'], name='api_grand_m_code_so_7bc10f_idx'),
        ),
        migrations.AddIndex(
            model_name='grand_materiel',
            index=models.Index(fields=['code_type_marque'], name='api_grand_m_code_ty_ac8103_idx'),
        ),
        migrations.AddIndex(
            model_name='grand_materiel',
            index=models.Index(fields=['code_filiale_g'], name='api_grand_m_code_fi_9d8de5_idx'),
        ),
        migrations.AddIndex(
            model_name='grand_materiel',
            index=models.Index(fields=['est_bloque'], name='api_grand_m_est_blo_f8dc56_idx'),
        ),
        migrations.AddIndex(
            model_name='grand_materiel',
            index=models.Index(fields=['date_acquisition'], name='api_grand_m_date_ac_52b45a_idx'),
        ),
        migrations.AddIndex(
            model_name='grand_materiel',
            index=models.Index(fields=['designation'], name='api_grand_m_designa_80f189_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['affectation_id'], name='api_pointag_affecta_61b76b_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['mmaa'], name='api_pointag_mmaa_4759ed_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['est_bloque'], name='api_pointag_est_blo_69ba49_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['date_modification'], name='api_pointag_date_mo_2f2959_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['affectation_id', 'mmaa'], name='api_pointag_affecta_84f4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='situation_materiel',
            index=models.Index(fields=['affectation_id'], name='api_situati_affecta_76a9d1_idx'),
        ),
        migrations.AddIndex(
            model_name='situation_materiel',
            index=models.Index(fields=['type_situation_id'], name='api_situati_type_si_7aebf6_idx'),
        ),
        migrations.AddIndex(
            model_name='situation_materiel',
            index=models.Index(fields=['code_type_etat_materiel'], name='api_situati_code_ty_3ef3b9_idx'),
        ),
        migrations.AddIndex(
            model_name='situation_materiel',
            index=models.Index(fields=['date_situation'], name='api_situati_date_si_c9190d_idx'),
        ),
        migrations.AddIndex(
            model_name='situation_materiel',
            index=models.Index(fields=['est_bloque'], name='api_situati_est_blo_6ab476_idx'),
        ),
        migrations.AddIndex(
            model_name='situation_materiel',
            index=models.Index(fields=['affectation_id', 'date_situation'], name='api_situati_affecta_d4c4a8_idx'),
        ),
    ]
